### ISSUE TITLE
Translation and cache

### ISSUE THREAD

**Issue by karl-police** [horyu1234/SCPLIST-KR-Translations#30]
I was looking for a github for the server list, to ask if stuff like this

![image](https://github.com/horyu1234/SCPLIST-KR-Translations/assets/12023782/8a4dea8f-9eaa-4c9b-83bb-65edc362c0e8)

can be saved into cookies, but *shrug*

but how do the translation things work, at the bottom of the page it says something, what is even the main language?

**Comment by horyu1234** [comment]
I can't understand the exact intent of the question, so I will understand and answer as asking how to translate.

We update the translation data on the production site at regular intervals when files for languages ​​are modified or new language files are added on this Github

**Comment by horyu1234** [comment]
The default language setting follows the user's browser's default language setting, and the setting is stored in a browser cookie.

**Comment by karl-police** [comment]
> The default language setting follows the user's browser's default language setting, and the setting is stored in a browser cookie.

I think one of the things is not being saved.

**Comment by horyu1234** [comment]
@karl-police We've updated the system to primarily save language settings in localStorage and updated the related module version. If the same issue reoccurs, please reopen the issue.
