### ISSUE TITLE
Player number information on a server does not update in real time

### ISSUE THREAD

**Issue by pinzis** [horyu1234/SCPLIST-KR-Translations#44]
I've recently noticed that the number of players on a server is a few hours behind and stuck at a fixed number for a while.

**Comment by horyu1234** [comment]
@InziDeveloperMode Does the graph of the number of servers come out normally?

**Comment by pinzis** [comment]
> @InziDeveloperMode Does the graph of the number of servers come out normally?

No, is blocked

**Comment by horyu1234** [comment]
@InziDeveloperMode Please upload the problematic server ID and screenshots.

**Comment by horyu1234** [comment]
And what browser are you using?

**Comment by pinzis** [comment]
> @InziDeveloperMode Please upload the problematic server ID and screenshots.

all servers are blocked

**Comment by pinzis** [comment]
> And what browser are you using?

Safari, Chrome, Opera GX

**Comment by horyu1234** [comment]
@InziDeveloperMode 
The word blocked is too vague. Please provide screenshots, etc. to explain the current situation. I don't see any problems.

**Comment by pinzis** [comment]
> @InziDeveloperMode 
> 
> The word blocked is too vague. Please provide screenshots, etc. to explain the current situation. I don't see any problems.

the number of players remains stationary and does not update, the graph remains stationary and does not update.![image](https://github.com/horyu1234/SCPLIST-KR-Translations/assets/98975836/720fcc50-de02-4663-8bab-ca5a21b56d2d)

**Comment by horyu1234** [comment]
@InziDeveloperMode 
Please reply with the URL of the site with the problem.

**Comment by pinzis** [comment]
> @InziDeveloperMode 
> 
> Please reply with the URL of the site with the problem.

Emh? https://scplist.kr

**Comment by lucastwg** [comment]
+1, all servers seem to update incorrectly if at all. The whole site is broken

**Comment by lucastwg** [comment]
![imagen](https://github.com/horyu1234/SCPLIST-KR-Translations/assets/57829093/c6df036f-353a-450c-8345-f3f9b4c1b5dd)

Here is a screenshot of a random server, it happens with all of them. After march 1st the whole site has become inconsistent.

**Comment by horyu1234** [comment]
@InziDeveloperMode @lucastwg I found an error in the update due to missing isoCode in the information coming from the official api. I'll fix it soon.

**Comment by horyu1234** [comment]
The resolution has now been completed. Please check if the issue has been resolved.

**Comment by pinzis** [comment]
> The resolution has now been completed. Please check if the issue has been resolved.

ok, problem solved, thanks!

**Comment by pinzis** [comment]
can you see this pull request? https://github.com/horyu1234/SCPLIST-KR-Translations/pull/45
